version: '2.1'
services:
  mongodb-server:
    image: mongo:3.4.10-jessie
    expose:
      - "27017"

  redis-server:
    image: redis:3.2.9-alpine
    expose:
      - "6379"

  mysql-server:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","--silent"]
      interval: 5s
      timeout: 10s
      retries: 5

  zookeeper-server:
    image: zookeeper:3.4.9
    expose:
      - "2181"
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "/zookeeper-3.4.9/bin/zkServer.sh", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  skywalking-webui:
    image: skywalking/skywalking-ui:3.2.4-2017
    expose:
      - "8080"
    ports:
      - "58080:8080"
    links:
      - skywalking-collector
    depends_on:
      skywalking-collector:
        condition: service_healthy
    environment:
      - COLLECTOR_SERVERS=skywalking-collector:10800

  skywalking-collector:
    image: skywalking/skywalking-collector:3.2.4-2017
    expose:
      - "10800"
      - "11800"
      - "12800"
    ports:
      - "12800:12800"
      - "11800:11800"
      - "10800:10800"
    depends_on:
      es-server:
        condition: service_healthy
      zookeeper-server:
        condition: service_healthy
    links:
      - es-server
      - zookeeper-server
    environment:
      - ZK_ADDRESSES=zookeeper-server:2181
      - ES_ADDRESSES=es-server:9300
      - BIND_HOST=skywalking-collector
      - UI_BIND_HOST=skywalking-collector
      - CLUSTER_BIND_HOST=skywalking-collector
    healthcheck:
      test: ["CMD", "curl", "-f", "http://skywalking-collector:10800/agentstream/grpc"]
      interval: 10s
      timeout: 10s
      retries: 5

  es-server:
    image: elasticsearch:5.3
    command: "-Enode.name=TestNode -Enetwork.host=0.0.0.0 -Ehttp.cors.enabled=true -Ehttp.cors.allow-origin=* -Ethread_pool.bulk.queue_size=1000 -Ecluster.name=CollectorDBCluster"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 5

  skywalking-agent:
    image: skywalking/skywalking-agent:3.2.4-2017

  cache-server:
    image: skywalking/test-cache-server:3.2.4-2017
    links:
      - "mongodb-server"
      - "redis-server"
      - "zookeeper-server"
      - "skywalking-collector"
    depends_on:
      zookeeper-server:
        condition: service_healthy
    environment:
      - MONGO_HOST=mongodb-server
      - REDIS_HOST=redis-server
      - ZK_ADDRESS=zookeeper-server:2181
      - COLLECTOR_SERVERS=skywalking-collector:10800
    volumes_from:
      - skywalking-agent

  presistence-server:
    image: skywalking/test-persistence-server:3.2.4-2017
    links:
      - "mysql-server"
      - "zookeeper-server"
      - "skywalking-collector"
    depends_on:
      mysql-server:
        condition: service_healthy
    environment:
      - MYSQL_ADDRESS=mysql-server:3306
      - ZK_ADDRESS=zookeeper-server:2181
      - COLLECTOR_SERVERS=skywalking-collector:10800
    volumes_from:
      - skywalking-agent

  portal-service:
    image: skywalking/test-portal:3.2.4-2017
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - "presistence-server"
      - "cache-server"
      - "skywalking-collector"
    environment:
      - ZK_ADDRESS=zookeeper-server:2181
      - COLLECTOR_SERVERS=skywalking-collector:10800
    volumes_from:
      - skywalking-agent
